### ISSUE TITLE
Cannot access local variable 'parent_id'

### ISSUE THREAD

**Issue by zetriqq** [EduAndino17/jellybean#1]
Hello, I receive the following error in the console:

C:\Users\Administrator\Desktop\4kinfo>py run.py
Movies - 4K
View Name: Movies
View Name: Music
View Name: Shows
View Name: Live TV
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\4kinfo\run.py", line 419, in <module>
    main()
  File "C:\Users\Administrator\Desktop\4kinfo\run.py", line 84, in main
    libraries_dict.update({library: {"parent_id": parent_id, "collection_type": collection_type}})
                                                  ^^^^^^^^^
UnboundLocalError: cannot access local variable 'parent_id' where it is not associated with a value

I put the api and server address in .env, I left the confg default. How could I fix it? TNX!

**Comment by EduAndino17** [comment]
Hi. I just pushed an update with improved error handling, can you git pull and try again? Also, make sure your library names match the `config.yaml`

**Comment by zetriqq** [comment]
I get this now:

C:\Users\Administrator\Desktop\4kinfo>py run.py
Movies - 4K
Movies - 4K Dolby Vision
TV Shows - 4K
TV Shows - 4K Dolby Vision
Checking Movies - 4K
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\4kinfo\run.py", line 450, in <module>
    main()
  File "C:\Users\Administrator\Desktop\4kinfo\run.py", line 109, in main
    items = get_all_items_library(libraries_dict[library])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\4kinfo\run.py", line 244, in get_all_items_library
    items = response.json()["Items"]
            ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I say that the library on jellyfin coincides with the config. I put a picture here: https://i.imgur.com/472ot9X.png

**Comment by EduAndino17** [comment]
can you please paste the log?`logs/jellybean.log`?

**Comment by zetriqq** [comment]
2023-06-16 17:55:16,201 - INFO - Admin user ID: 7eb37e416fb04c458b0086b24af93059
2023-06-16 17:55:16,203 - INFO - Lodaded config.yaml:
Libraries: {'Movies - 4K': {'overlays': True, 'skip': True}, 'Movies - 4K Dolby Vision': {'overlays': True, 'skip': True}, 'TV Shows - 4K': {'overlays': True, 'skip': False}, 'TV Shows - 4K Dolby Vision': {'overlays': True, 'skip': False}}
2023-06-16 17:55:24,288 - INFO - Checking Movies - 4K


Do I need to have a separate library for 4k called "Movies - 4K"? Now I saw that this is what it's called, I thought it would search through movies and change for 4k movies, if necessary is my mistake, sorry XD

**Comment by EduAndino17** [comment]
Correct :) Jellybean is looking for `Movies - 4K` as per your `config.yaml`. Edit your config to match your Jellyfin libraries.

Right now it is intended to work on 4K only Libraries as it does not check the resolution..yet.

**Comment by EduAndino17** [comment]
No worries, will add better explanation on the config ;)
